### ISSUE TITLE
Can't compile on Java 6

### ISSUE THREAD

**Issue by kristiank** [BaseXdb/basex#1077]
I am not a Java developer, so please bare with me.

The documentation states in a few places, that BaseX is compatible with Java 6 / JDK 1.6, but that the downloadable automatically built [latest stable war-file](http://files.basex.org/releases/latest/) need's Java 7.

Is it possible to compile against Java 6? I have tried following your Maven documentation and a fresh git clone of your code, but ``mvn compile`` ends in an error stating ``invalid target release 1.7``. I tried changing the number in the ``pom.xml`` file, but then getting syntactical errors. I'm afraid this is as far as my Java knowledge goes.
I get the same ``invalid target release 1.7`` error when following the [Web Application compilation guide](http://docs.basex.org/wiki/Web_Application#Servlet_Container)

We have JRE 1.6.0-34 OpenJDK on our production server and can not upgade to Java 7.

**Comment by dirkk** [comment]
Starting with BaseX 8 we dropped support for Java 6. Java 6 did not receive public updates from Oracle since nearly 2 years and has received its end of life. Actually, even Java 7 is nearingits end of life in April this year.

So no, there is no way to make this work. If you stay with Java 6 you will have to use BaseX 7.9.

Also, please use the mailing list for support questions as we use the issue tracker on GitHub solely for bug-tracking tickets and similar.

**Comment by ChristianGruen** [comment]
Hi Kristian, thanks for the hint; I have updated our documentation. As Dirk said, BaseX requires Java 7.
