### ISSUE TITLE
RESTXQ: Multiple operations per request

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1143]
Currently, one RESTXQ function is selected and evaluated per client request. Some operations, such as authentication or logging, need to be evaluated by more than one, if not all, requests. In these cases, it would be helpful to have global RESTXQ functions that are evaluated before or after the actual request. The same applies to serialization parameters: It would be handy if repeatedly used annotations could be specified only once.

One solution would be to introduce new `%rest:before-path` and `%rest:after-path` annotations:

``` xquery
declare %rest:before-path("main/{$path=.*}") function local:init($path) {
  (: check if user is logged in. if not, raise an exception :)
  user:check()
};

declare %rest:path("main/dashboard") function local:main() {
  'Hello there!'
};

declare %rest:after-path("{$path=.*}") function local:finalize($path) {
  admin:write-log("Operation was successful.")
};
```

Challenges to be solved:
1. What to do if more than 1 function is selected as candidate (e.g. `{$any-path}` and `path`)?
   1. Only evaluate function with the most specific path (similar to `%path` annotation)
   2. Evaluate function with most general path first, then evaluate more specific one, etc.
2. What to do if more then 1 function with the same specifity is selected (e.g. `path` and `path`)?
   1. Raise error
   2. Dodgy: evaluate functions in the order they have been parsed.
3. How to handle updates performed by `%before-path` or `%after-path` functions
   1. Raise error
   2. Perform update (…affects next query, transactional semantics, etc.)
4. How to handle results returned by `%before-path`:
   1. Raise error
   2. Ignore result
   3. Return result (might e.g. lead to conflicts if different serialization parameters are specified)
   4. Return result, do not process actual function (somewhat magic, as the same function may or may not return something)
5. How to handle results returned by `%after-path`:
   1. Raise error
   2. Ignore result
   3. Return result (serialization parameters, see above)

Raising errors would be the most restrictive approach. It could be a good start, and more flexibility could be added later.

**Comment by xokomola** [comment]
I have doubts if this is the right solution for the problems it is trying to solve.

- Having multiple entry points to a request makes things more complicated. Instead of a request matching one handler it may match multiple and it may be hard to track which handlers are hit by each request and in which order.

- Many of the challenges you mention are a direct consequence of this and thus may lead to incidental complexity or needless constraints in order to deal with these challenges.

I would very much like to see other proposals for the same problem in order to find out if they have the same, less, or more challenges.

In my view RESTXQ is meant to route a URL to a handler and providing some help in dealing with HTTP requests and responses.

There are other approaches to learn from. One such interesting concept is that of middleware functions. It is featured in many successful web frameworks for Python, Ruby,  Clojure and others. In my Fold project I am experimenting with this approach for XQuery. In Fold I use RESTXQ to take a request, marshall it into a map and deliver it to a handler function. Which in turn might send it to another nested handler function and so on.

So cross-cutting concerns such as authentication, authorization are dealt with by wrapping (or composing) the handler function in functions that only deal with these aspects. This also means that these wrapper functions get the HTTP request before it hits the next handler, but they can also modify the HTTP response (also a map) when it comes back from a handler. If you look at web frameworks that use this approach you can see that it leads to a nice separation of concerns and adding a new handler in the "pipeline" of handlers is very easy. So you could have a handler that only deals with sessions or for development you could instrument your handler "pipeline" with a code-reloading middleware.

I think RESTXQ is a standard, it's very good and also simple to learn. It's the approach I use in production. I am not so sure if I would like to see it become more complicated. REST services or Web apps may need more control over the handling and routing of a request but I am doubtful that introducing different path handling annotations and their rules of interaction (to deal with specificity, error handling) are the answer. I would opt for keeping RESTXQ simple, deal with the HTTP request and HTTP response but stay out of the business of handling application logic.

**Comment by dcore94** [comment]
I totally agree with xokomola's comments. The handler pipeline is something we also use when it comes to configure things like logging, tenancy routing, soap (un)wrapping.

**Comment by ChristianGruen** [comment]
Thanks @xokomola and @dcore94 for your comments. I see we should rethink this again.

**Comment by ChristianGruen** [comment]
Closed for now.
