### ISSUE TITLE
Error while parsing a valid json string

### ISSUE THREAD

**Issue by ab34** [BaseXdb/basex#1145]
Considering the following query:

```xquery
json-to-xml('{
  "string": "this is a valid 'json quoted string'",
  "source": "RFC 7159 JSON Grammar",
  "url":"http://tools.ietf.org/html/rfc7159"
}')
```
Result: 
```text
[XPST0003] Expecting closing bracket for function 'json-to-xml'
```
This is an error on the ' character, apparently.

Expected output:
```xml
<map xmlns="http://www.w3.org/2005/xpath-functions/json">
  <string key="string">this is a valid 'json quoted string'</string>
  <string key="source">RFC 7159 JSON Grammar</string>
  <string key="url">http://tools.ietf.org/html/rfc7159</string>
</map>
```

**Comment by ChristianGruen** [comment]
Nope; you need to escape `'`, because it otherwise conflicts with the XQuery apostroph. This version is valid:

```xquery
json-to-xml('{
  "string": "this is a valid ''json quoted string''",
  "source": "RFC 7159 JSON Grammar",
  "url":"http://tools.ietf.org/html/rfc7159"
}')
```

Please write to the mailing list as long as an error has not been confirmed.

**Comment by ab34** [comment]
This is not how Github works (public repositories where anyone can post issues about repositories), but I take your point.

Your version of the query indicates that the json parsing from xquery can not deal with some valid json strings according to the json specification.

**Comment by ab34** [comment]
That's fine, I won't participate to the repository anymore, as it seems that it is assimilated to a private repository. 

It is just not very elegant to force people to write into some mailing lists, when they already are in a public discussion place. Anyway thanks for the work on BaseX and good continuation.

**Comment by ChristianGruen** [comment]
> Your version of the query indicates that the json parsing from xquery can not deal with some valid json strings according to the json specification.

This has nothing to do with json parsing in XQuery.  Conflicting apostrophes and quotes always need to be encoded, no matter which language you use. One more example: Think of the valid string `'"`, and then try to write an XQuery expression (or Java or whatever code) that represents and returns this string. In XQuery, this would look like `'"'''`, in Java it would be `"\"'"`.

If you e.g. store your JSON document in a file (e.g. `example.json`) and open it in your query (`json-to-xml(unparsed-text('example.json'))`), there will be no need to encode your string.

**Comment by ChristianGruen** [comment]
> This is not how Github works (public repositories where anyone can post issues about repositories), but I take your point.

I'm sorry for forcing you into something you are not comfortable with. On the other hand, most people seem to be completely fine with it. Over the years, I have learned about enough other open source projects, and all of them have their own rules, based on the experiences developers have made in the past, based on the amount of feedback they get, and based on personal preferences as well. Some projects provide public forums, wikis, issue trackers, user groups or whatever; some provide  nothing at all (which may be called "inelegant" as well). In my point of view, it doesn't have to with technical features of GitHub or any other platform and what is public or private. Instead, it's mostly about organizing workloads.

Things may evolve. Once you have found some real bugs in BaseX, you may be invited to post them here (and, ideally: even fix them, because our code base is public as well ;).

**Comment by ab34** [comment]
That's all I needed to hear, thanks. No need then to modify the xquery parsing algorithm in order to deal with json quoted strings. And good to hear that there is no need to escape the json string when it is read from disk. Thanks for the clarification.

No meaning any offense with the "inelegant" qualificative. I understand the point about work organization and preferred workflows. Thanks for letting me know equally. Though I'm not comfortable with many things that most people takes for granted, I'm comfortable with silence, so that's fine. ;)
