### ISSUE TITLE
Bad optimization of static part in predicate

### ISSUE THREAD

**Issue by JensErat** [BaseXdb/basex#1160]
In a [Stack Overflow question](http://stackoverflow.com/q/30798336/695343) BaseX showed up to optimized this particular query very badly, not precomputing the whole static inner part of the predicate. The original query takes around 30 seconds on the linked document:

    /root/PlSpTys/PlSpTy[
      isOfPlGeTy/@href=/root/PlGeTys/PlGeTy[
        isOfPlCt/@href=/root/PlCts/PlCt[
          environment='AIR'
        ]/@id
      ]/@id
    ]

While pulling out the right-hand-side of the comparison in the outermost predicate reduces evaluation time to 16ms:

    let $compare :=
      /root/PlGeTys/PlGeTy[
        isOfPlCt/@href=/root/PlCts/PlCt[
          environment='AIR'
        ]/@id
      ]/@id
    
    return
      /root/PlSpTys/PlSpTy[
        isOfPlGeTy/@href=$compare
      ]

Tested against BaseX 8.1.1 and 8.2.1.

**Comment by ChristianGruen** [comment]
Precise analysis of the problem… Yes, this optimization has been discussed before. It's sometimes difficult to statically estimate if the precomputed result won't be too large to be cached, and it will really be required. Just look at the example above: It could be that there are millions of nodes with the environment "AIR", and the equality expression can already be skipped once the first matching node has been found.

But, still, we should find a solution to that, because the above pattern is frequently found in pure XPath queries.

**Comment by ChristianGruen** [comment]
I have now implemented a solution that caches the result of a path expression if it is requested at least twice. Caching is only allowed if the path does not contain any non-deterministic expressions and if the initial context value does not change. The snapshot will be available soon.
