### ISSUE TITLE
Optimiser drops variable that shouldn't be dropped.

### ISSUE THREAD

**Issue by LukasK** [BaseXdb/basex#1212]
Seen in `BaseX 8.3.1` and `BaseX 8.4 beta fb02686`:

Query:
```xquery
let $f := function() {
  fn:error(xs:QName(""), 'you should see _this_')
}
let $ok := $f()
return "you shouldn't see this."
```

Result:
```
you shouldn't see this.
```

**Comment by ChristianGruen** [comment]
Should be fine, because $f() will never be accessed. However, I would need to find the correct hint in the spec to prove it. A little hint: the query is also accepted by Saxon and Zorba. And another hint: `xs:QName("")` is already invalid, so…

```xquery
fn:error(xs:QName(""), 'you should see _this_')
```

…will give you `[FORG0001] Cannot cast xs:string to xs:QName: "".` ;)

**Comment by LukasK** [comment]
Ok - so if we look at this isolated use cases I see the point. I edited this down from a lot more code. What about this:

```xquery
let $f := function(){ fn:error() }()
return ()
```

Why is the error then raised here?

**Comment by ChristianGruen** [comment]
I assume that both results would be legal, but I completely agree that the behavior is inconsistent here (only in BaseX, btw.). Maybe the general questions is how we should deal with non-deterministic code that is hidden inside function items (which are, as non-evaluated items, deterministic). As we skip optimizations for everything that’s non-deterministic, it would be consistent to evaluate every function item that contains non-deterministic code. Things are getting tricky, however, as soon as function items are not directly evaluated, but e.g. bound to variables. See the following example:

```xquery
  for $f in (function() { }, function() { error() })
  return $f()
```

I believe that we would eventually need to introduce a "non-deterministic" flag, similar to the updating flag:

```xquery
  (: evaluation of updating function item :)
  let $f := %updating function() { ... }
  return updating $f()
  (: evaluation of non-deterministic function item? :)
  let $f := %non-deterministic function() { error() }
  return non-deterministic $f()
```

Ideas are welcome…

**Comment by ChristianGruen** [comment]
One more comment on how to tackle this in productive code: It’s recommendable to avoid variable declarations if they won’t be referenced in the remaining query. Your original query could be rewritten as follows:

```xquery
let $f := function() {
  fn:error((), 'you should see _this_')
}
return ($f(), "you shouldn't see this.")
```

**Comment by ChristianGruen** [comment]
Good proposal resulting from the discussion with @dirkk: Introduce new keyword `non-deterministic` to mark function calls as non-deterministic:

```xquery
let $f := function() { error() }
let $enforce-execution := non-deterministic $f()
return ()
```

To be strict, it would be more precise to talk about *side-effecting* functions (but there is currently no such distinction in BaseX: everything that causes side effects is flagged as non-deterministic).

**Comment by dirkk** [comment]
I'd still vote for using `side-effecting`, even if it does the same thing at the moment. However, changing a keyword later is always complicated as it breaks code. And maybe at some point in the future we are going to make a distinction between non-deterministic and side-effecting.
Also, I find it easier to understand as a application developer. In the given example, it feels quite confusing to use `non-deterministic`, because function `$f` is deterministic.

**Comment by ChristianGruen** [comment]
One reason for having non-deterministic functions is that they are defined in the [XQFO spec](http://www.w3.org/TR/xpath-functions-31/#dt-nondeterministic) anyway. If we additionally introduced side-effecting functions, we’d need to clearly differ between these two types, and this sounds like a lot of work. Back then, the Zorba team had put quite some effort in this distinction.

**Comment by dirkk** [comment]
Well, but looking at the spec non-deterministic is defined as:

 > [Definition] A function that is guaranteed to produce identical results from repeated calls within a single execution scope if the explicit and implicit arguments are identical is referred to as deterministic.

By this definition, the function `$f` from above is clearly deterministic. Therefore, I think, it would be highly confusing to declare this function non-deterministic, when it is in fact not. 

In the beginning it would be totally fine if the effect of side-effecting functions would be the same as for non-deterministic ones with the additional requirement proposed here to not be dropped by optimizing.

**Comment by ChristianGruen** [comment]
You are right that $f itself is non-deterministic… As long as it is not called (fn:error is defined as non-deterministic in the XQFO spec).

**Comment by ChristianGruen** [comment]
A little addition: The keywords "updating" (and, possibly in the future, "non-deterministic") do actually not refer to the function, but the function call.

**Comment by ChristianGruen** [comment]
In a dynamic function call, a function can now be flagged as `non-deterministic`:

```xquery
let $f := function() { error() }
return non-deterministic $f()
```

This way, optimizations that are usually applied to deterministic code will be skipped.

Apart from that, analysis of non-determinististic code has generally been improved. As a result, the query shown in the initial comment in this issue will now raise an error. There are limits to this, however. For example, the following expression will terminate successfully, because `$ignored` is not referenced, and `$f` will only be bound at runtime:

```xquery
for $f in (prof:void#1(?), error#0)
let $ignored := $f()
return ()
```
