### ISSUE TITLE
Error message in dba "Jobs & Users"

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#1321]
I've seen this error several times in DBA after logging in to DBA and clicking on "Jobs & Users". The error disappears after going back and trying again.

<pre>
HTTP ERROR 400

Problem accessing /dba/jobs-users. Reason:

    Stopped at C:/Programs/BaseX/basex/webapp/dba/jobs-users/jobs-users.xqm, 92/41:
[bxerr:BXSE0002] Stored attribute cannot be retrieved: QueryContext.

Stack Trace:
- C:/Programs/BaseX/basex/webapp/dba/jobs-users/jobs-users.xqm, 32/10

Powered by Jetty://
</pre>

**Comment by ChristianGruen** [comment]
I think the problem is fixed now (although I couldn’t provoke it by myself). Could you please replace `jobs-users.xqm` with the [new version](https://github.com/BaseXdb/basex/blob/64ee8ce3b63083195e28d4b2d44f75ffe9280df3/basex-api/src/main/webapp/dba/jobs-users/jobs-users.xqm) and reopen the bug if the problem persists?

**Comment by vincentml** [comment]
That fixed it! In addition to after logging in, the error message would appear if I had dba open in two browser windows, run a long-running query in one window and go to Jobs & Users in the other window. I am not seeing the error message now with the new version. Thank you!!!
