### ISSUE TITLE
JSON serialization with forward slash '/'

### ISSUE THREAD

**Issue by james-jw** [BaseXdb/basex#1344]
Hope all is well!

Just updated to the latest release and noticed an issue with JSON serialization. The following:

```java
map {
  'uri': "test/test"
} => json:serialize()
```
results in:

```json
{ "uri": "test\/test" }
```

I would have expected:
```json
{ "uri": "test/test" }
```
Cheers!

**Comment by apb2006** [comment]
Hi James,  I think this is as expected see http://www.json.org/ string solidus.

**Comment by dirkk** [comment]
I am not sure. I personally find the spec here rather confusing. A map is serialized using the json output method as described in https://www.w3.org/TR/xslt-xquery-serialization-31/#json-output

It specifically states

> Any other character in the input string (but not a character produced by character mapping) is a candidate for Unicode Normalization if requested by the normalization-form parameter, and JSON escaping. JSON escaping replaces the characters quotation mark, backspace, form-feed, newline, carriage return, or tab by the corresponding JSON escape sequences \", \b, \f, \n, \r, or \t respectively, and any other codepoint in the range 1-31 or 127-159 by an escape in the form \uHHHH where HHHH is the hexadecimal representation of the codepoint value. Escaping is also applied to any characters that cannot be represented in the selected encoding.

So everything except the solidus and reverse solidus is escaped as it is explained in the json spec. I wonder about this discrepancy between the XQuery and the json spec. 

So to me it looks like BaseX behaves correctly according to the json spec, but not according to the XQuery spec.

**Comment by james-jw** [comment]
That must have changed recently? Never worked like that before nor does it any other JSON library I use including Javascript itself, any browser or .NET. I don't use Java much so maybe that's the catch. 

For example in node or any browser this works as expected:
```javascript
JSON.stringify("{ "uri": "test/test" })
```

resulting in ``{ uri: "test/test"}``

Basically you have to be really careful with JSON and this change since there is no way to cleanly go from JSON to XML and back without find/replace on the data knowingly unless there is a way around this?

How would I produce:
{
  "uri": "http://test.com/test",
}

Hopefully we can go with the XQuery spec as the JSON one is wonky. 
Cheers either way!

**Comment by apb2006** [comment]
After more research It seems this is a well known issue beyond XQuery see for example http://stackoverflow.com/a/1580682/3210344

**Comment by james-jw** [comment]
Yeah, I saw that stackflow post prior and as it appears to be related to Java's implementation in particular. I just personally have never run into this style of serialization. 

Not the end of the world, just everything we use assumes the former and it has been using the former for years now. It really only effects the easy of use in leveraging the API responses as a human since almost every json parse handles it correctly...

**Comment by dirkk** [comment]
Well, the answers even point out that you can escape a solidus, but you _have_ to escape a reverse solidus. And then they say XML is complicated and weird...

However, I would support James' request to get rid of the escaping of solidus as I find it rather cumbersome as well. But we will have to wait until Christian returns from vacation to decide this. I didn't look into it were this change was intruced, maybe it was in fact just by accident, maybe it was intentional...

**Comment by james-jw** [comment]
Well thanks for reaching out guys. I guess we will see what Christian thinks! Luckily it doesn't cause things to stop working :)

**Comment by apb2006** [comment]
```
map {
  'uri': "test/test"
} => json:serialize(map{"escape":false()})
```
http://docs.basex.org/wiki/JSON#json:serialize Version 8.4    Updated: unescape changed to escape.

**Comment by james-jw** [comment]
Nice! I was looking at the XQuery 3.1 documentation and not the JSON module documentation. DOH!!

**Comment by james-jw** [comment]
And with the RESTXQ its:

```java
%output:method("json") 
%output:json('escape=false')
```

Thanks again Andy and Dirk!

**Comment by dirkk** [comment]
Thanks Andy. We should definitely improve our documentation here as it is quite unclear whether there might be even more JSON-specific options (that's also why I am not going to add it myself). Definitely it is not sufficiently to only have it in the changelog - But awesome that you found it anyways (But I am quite ashamed of it, because I am quite sure Christian showed it to me some time ago, but I couldn't really remember. But anyways, given that not everyone sits in the same office as Christian we should improve our documentation :)

I am going to close this because given the escape parameter I am quite sure the change was intentional.

**Comment by ChristianGruen** [comment]
Hi there, solidus escaping has recently been changed by the W3C [1,2]. It usually takes a time for the new spec to be made public. @dirkk: No worries, I’m pretty sure I didn’t talk about this update… I didn’t add any comment to our spec, because it’s one of those many updates that will eventually be visible in the official W3 documents. One more change, for example: The functions map:remove and array:remove can now remove multiple entries/members in a single call.

[1] https://www.w3.org/Bugs/Public/show_bug.cgi?id=29665
[2] https://github.com/BaseXdb/basex/commit/174db27dd346696b546ee259dbc53d280a740142
