### ISSUE TITLE
Long query evaluation times with modules

### ISSUE THREAD

**Issue by clemensm** [BaseXdb/basex#1428]
Hello BaseX team

I think I might have found an issue with rather long query evaluation times when using modules. After some work I've ben able to create a minimal example that demonstrates the issue. I am mainly working on BaseX 8.6, but I've also verified the issue on BaseX 8.6.1.

In the attached zip file you can find everything required to reproduce the issue with these steps:

1. Create a new database with default settings and add all files in the xml directory. Note that the files dg_16_es.xml etc are not required by this example, but they are present in the production db and make the issue more pronounced.
2. Import the two script in the repo dir into the base repo. First the proof-utils.xq, then basic-proof.xq
3. Run the example file script.xq. This will output two simple Maps with a few messages that have been read from the database (keys "Name" and "Msg"). The running time on my machine is ~70 ms for this configuration.
4. Open the file basic-proof.xq and at the very bottom there are two lines, one is commented. Switch the comments on the two lines.
5. In the file script.xq comment the line with the active return and uncomment the last three lines instead.
6. Run the script.xq again. Running time should now be somewhere around ~5-10ms. 

So all I do here is move the final function call that reads some messages from the db and attaches them to the maps from the module file to the script, but still calling the same function. Note that in production we do this not only for two or three maps but  for way more, where I can regularly see times in the order of 3-10 seconds just for fetching the messages.

[bug_basex.zip](https://github.com/BaseXdb/basex/files/807167/bug_basex.zip)

**Comment by clemensm** [comment]
I forgot to add that I times this using the GUI, and the times I mentioned above are total times. However the difference was in the third column, i.e. the evaluation time.

**Comment by ChristianGruen** [comment]
Hi Clemens, I will look into this soon. A general note: Please write to the [basex-talk mailing list](https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk) to discuss unconfirmed bugs and feature request.

**Comment by clemensm** [comment]
Hi Christian
Thanks. Sorry about the bug, I did not know that you are using the mailing list for that. I'll use that one for potential bugs in the future then.

**Comment by ChristianGruen** [comment]
Hi Clemens, I had time to look at your query:

* The BaseX XQuery compiler inlines functions to speed up query evaluation and allow for further optimizations (see http://docs.basex.org/wiki/XQuery_Extensions#basex:inline).
* In your initial query, the function `basic-proof:execute` exceeds the inline limit.
* As described in the upper Wiki link, you can assign a `%basex:inline` annotation to this function to enforce function inlining.
* As as result, a nested database access (`db:open($db)//conditions[@country = $country and @year = $year]`) will be rewritten for index access (as can be seen by the hidden `applying attribute index for $country_62` message in the GUI Info View, or by specifying -V on command line), because it can be detected at compile time what database `$db` refers to, and if this database has an up-to-date index structure.

Hope this helps.

**Comment by clemensm** [comment]
Hi Christian

Thanks, that fixed the issue. I think I'll try to understand more about inlining now :-)

Clemens
