### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by SebastianZimmer** [BaseXdb/basex#1441]
I want to send requests to the BaseX REST API via AJAX/fetch from a website on a different domain. For this to work, BaseX would need to send an `Access-Control-Allow-Origin` HTTP header with its responses. Currently, there seems to be no built-in way to do this, thus this feature request to allow CORS.

Related: http://stackoverflow.com/questions/42932689/basex-rest-api-set-custom-http-response-header

**Comment by ChristianGruen** [comment]
Hi Sebastian, Could you please confirm if the StackOverflow solution provided by @JensErat met your requirements? If yes, I will embed it in future versions of BaseX (the `jetty-servlets` has already been requested by another user; it’s also required for sending compressed data).

**Comment by dirkk** [comment]
I think adding the `jetty-servlets` is very reasonable, but I would avoid enabling CORS by default (as Jens suggested in his SO answer). To disable this is a basic security measure and I think basically all HTTP servers disable this by default. Hence, I don't think we should do it differently because we don't really know more about HTTP servers than the HTTP server guys.

But of course there are many valid use cases for doing so, so to simplify it for the user to enable CORS is a good thing.

**Comment by SebastianZimmer** [comment]
The solution by @JensErat works for me.

I agree with @dirkk that CORS should not be enabled by default.

**Comment by ChristianGruen** [comment]
Resolved. Feel free to check out the [latest stable snapshot](http://files.basex.org/releases/latest/).
