### ISSUE TITLE
Astral code points

### ISSUE THREAD

**Issue by VincentBiragnet** [BaseXdb/basex#1459]
Basex is ok to handle this query 
`file:write( 'C:\odd.xml', element{codepoints-to-string(128512)}{'test'})`
But fails to read the newly created file, e.g. using this query
`doc("C:\odd.xml")`

It seems that some astral code points (above \uffff) are OK in XML Names (cf [here](https://www.w3.org/TR/REC-xml/#sec-common-syn)).

**Comment by ChristianGruen** [comment]
Apparently this limitation is due to Java’s XML parser, which is by default used to parse XML files. You can use the internal BaseX parser instead (by setting [INTPARSE](http://docs.basex.org/wiki/Options) to true), or work with `fetch:xml` instead:

```xquery
fetch:xml('C:\odd.xml', map { 'intparse': true() })
```

Hope this helps, CG.

PS: Mails to our `basex-talk` mailing list are preferred.
