### ISSUE TITLE
GUI, Editor, quote completions

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1512]
Closing quotes are automatically added. No insertion should take place if previous character is already a quote.

**Comment by dirkk** [comment]
One wish: I would love if inserting a quotes also checks whether inserting the quote might make the query valid. I quite often insert leading quotes, which is always quite annoying because the closing quotes are added automatically. For example, when I have

    doc(test.xml")

i would be nice if inserting the missing quote in the front would not lead to

    doc(""test.xml")

**Comment by ChristianGruen** [comment]
As the text completion code is pretty low-level, it would be tricky to do trigger more complex validations. I have extended the code to a simple check if the next character is no “XML letter” ([NameChar](https://www.w3.org/TR/xml/#NT-NameChar)).
