### ISSUE TITLE
implicit casting strange behaviour

### ISSUE THREAD

**Issue by sofiageo** [BaseXdb/basex#1525]
Hi,
I'm not sure if this is a bug or not, but I thought I should report it. The following code gives strange results, but I'm not an expert on the casting rules. Tested on latest snapshot.

1) The following code returns an error.
```
let $x := <result><isPreTax>false</isPreTax></result>
let $bool as xs:boolean := $x/isPreTax
return prof:type("test")
```
2) The following code doesn't
```
let $x := <result><isPreTax>false</isPreTax></result>
let $bool as xs:boolean := $x/isPreTax
return prof:type($bool)
```

I've also tried the second example (by returning the $bool variable) on Saxon 9.8 and it gives an error. So I'm confused here.

**Comment by ChristianGruen** [comment]
This was a little bug: Texts cannot be treated as booleans, but must be explicitly converted.

Your two expressions were evaluated differently due to various internal rewritings:

* In the first query, the second `let` clause was optimized away. Before removing the clause, a type check was performed, which correctly raised an error.
* In the second query, `$bool` was evaluated, and the subsequent type check treated the value as if it was a function argument. It may come as a surprise that the following expression is indeed valid:

```xquery
declare function local:result($bool as xs:boolean) as xs:string {
  "Result: " || $bool
};
local:result(<x>true</x>)
```
