### ISSUE TITLE
basex/dba docker image is out of sync with basex/basexhttp

### ISSUE THREAD

**Issue by HitkoDev** [BaseXdb/basex#1527]
basex/dba automated build is set to checkout tag 8.5.4, however it uses `FROM basex/basexhttp:latest`, which is built from master branch. This causes the dba interface to be out of sync with the server, and, in recent releases, nonoperational. 

Whoever is in charge of https://hub.docker.com/u/basex/ should properly configure automated builds (i.e. change SourceRef from '8.5.4' to 'master') to fix this issue.

**Comment by ChristianGruen** [comment]
Maybe it would be advisable to discard this particular Docker image, as the more recent versions of DBA rely on local database instances. @JensErat: Do you have some thoughts on that?

**Comment by ChristianGruen** [comment]
The alternative I guess would be to change `FROM basex/basexhttp:latest` to `8.5.4`.

**Comment by HitkoDev** [comment]
Since the build is tagged `latest`, the proper way would be to checkout master. Using `FROM basex/basexhttp:8.5.4` would be appropriate for `basex/dba:8.5.4`.

**Comment by ChristianGruen** [comment]
Thanks for the hint. So we should probably remove the latest build. I’ll try to find out who can do this change.

**Comment by HitkoDev** [comment]
Why remove it? We could just copy the `basex/basexhttp` pattern and have tagged builds for each release, plus a `latest` build for the master / indev.

**Comment by ChristianGruen** [comment]
I remember there had been some reasons why a fixed tag number was applied (one reason might have been that [support for remote connections](https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg09064.html) is not supported anymore by newer versions of the DBA). Let’s wait for some more feedback on this issue.

**Comment by HitkoDev** [comment]
Support for remote connections shouldn't be a problem, as `basex/dba` is basically the same as `basex/basexhttp` + files from https://github.com/BaseXdb/basex/tree/master/basex-api/src/main/webapp/dba. 

From what I've seen, it seems the problem may be that automated builds don't support dynamic base image for now, so `FROM basex/basexhttp:latest` would have to be changed accordingly for each release. Manual builds could be solved with `docker build --build-arg version=8.5.4 .`

**Comment by ChristianGruen** [comment]
Thanks for your assessment.

**Comment by micheee** [comment]
Hi @HitkoDev ,
Hi @ChristianGruen 

> Support for remote connections shouldn't be a problem, as basex/dba is basically the same as basex/basexhttp + files from https://github.com/BaseXdb/basex/tree/master/basex-api/src/main/webapp/dba.

I think that is the point: @JensErat originally had the idea to separate `basexhttp` and our `dba` module, as before 8.5.4 (iirc) you could connect to any remote `basexhttp` instance via our `dba`-module.

You could start a (1)`basexhttp` that contained your application code **and** you could start an `dba `-instance, that happened to use `basexhttp`as well, to connect to your original (1)`basexhttp` instance.

In more recent releases `dba` will only work with its local/own `basex`-instance, so we fixed the `basex/dba` to the latest version that contained a `dba` that allowed remote connections.


Some first thoughts:

- [ ] building `dba` with `basexhttp:latest`, losing the ability to connect to another instance if the version used is higher than 8.5.4

or:

- [ ] removing `basex/dba` entirely **and**
  - [ ] _either_ adding the `dba` to the `BaseXWeb`-folder our default `basex/basexhttp` image, _or_
  - [ ] adding `dba` to our tags, maybe something like the following:
    - `basexhttp:8.7.4-dba`
    - `basexhttp:latest-dba`
    - so the user may decide if he/she wants to include the `dba` webapp

or:

- [ ] removing `basex/dba` entirely **and**
- [ ] allow users to easily install `restxq` modules such as the `dba` via an XQuery command? (maybe `REPO INSTALL …` can already do this?

---

I think I'd probably prefer the `REPO INSTALL …` variant; because most users will locally mount or overwrite the `BaseXWeb` folder to contain their own application code, `REPO INSTALL …` would save the `dba` to the users folder.

Maybe this might need some more thought and discussion.

**Comment by micheee** [comment]
> The alternative I guess would be to change FROM basex/basexhttp:latest to 8.5.4.

I made this change, as BaseX 8.5.4 is the last version to support remote DBA connections.

In later releases it is advisable to copy the latest DBA to the `basexhttp`-instance that is supposed to be administered.

**Comment by ChristianGruen** [comment]
As DBA 8.5.4 won’t run with BaseX 9.0 anymore, and as support for remote DBA connections was discontinued, we decided to remove the `latest` tag of [`basex/dba`](https://hub.docker.com/r/basex/dba/).

**Comment by micheee** [comment]
Seems like @HitkoDev  figured something out 🥇 

> Fix latest build (because f*** those guys)

https://github.com/Liquid-JS/basex/commit/9a9bcde222193b455a4459dc57edd4bb589c032f
