### ISSUE TITLE
Memory leak in 9.0.2

### ISSUE THREAD

**Issue by bufly** [BaseXdb/basex#1619]
I found a memory leak in BaseX 9.0.2. (using java libs)
Running this code (many times) causes memory leaking. Problem is obvoiusly in the 'if' block,
if there are two conditions - $i = 'a' or $i = 'd':

let $a := ('a', 'b', 'c', 'd', 'e', 'f')
return
  for $i in $a
  return
  if ($i = 'a' or $i = 'd') then
    "yes"
  else
    "no"

Note: If you remove the second condition ($i = 'd') then no leak appears.

Attached is a maven project.
I run it on Linux with command: java -Xmx10m -jar leak-0.0.1-SNAPSHOT-jar-with-dependencies.jar
After few seconds I get:

org.basex.core.BaseXException: Out of Main Memory.
        at org.basex.core.Command.execute(Command.java:94)
        at org.basex.core.Command.execute(Command.java:116)
        at leak.Main.main(Main.java:24)

[leak.zip](https://github.com/BaseXdb/basex/files/2345178/leak.zip)

**Comment by ChristianGruen** [comment]
I guess that the problem you observed has recently been fixed in 836eaae88586460512d80fdef5d57169d20f4b32. Could you please check out the latest snapshot (i.e., the `9.1-SNAPSHOT` artifact or [here](http://files.basex.org/releases/latest/)) or and verify if the problem persists on your system? Thanks in advance.

**Comment by ChristianGruen** [comment]
I believe the issue has been resolved. Thanks for reporting this.

**Comment by bufly** [comment]
Thank you, I tested the 9.1-SNAPSHOT version and the leak no more appears.
