### ISSUE TITLE
XQuery, fn:matches, 'j' flag not working in version 9.1.2

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#1669]
The 'j' option to use Java's regular expression parser is not working in BaseX 9.1.2 and produces an error message `[FORX0001] Invalid regular flag: 'j'.` although this option works in BaseX 9.1.1. 

This feature allows using the Java regex parser instead of the XQuery regex parser by adding "j" as a modifier flag in the third parameter of fn:replace. This feature was added with Issue #1608 and is described in [the BaseX' documentation](http://docs.basex.org/wiki/XQuery_Extensions#Regular_Expressions) 

I'm attaching a SSCCE [basex-regex-test.zip](https://github.com/BaseXdb/basex/files/2924034/basex-regex-test.zip) that shows the problem. Unzip the files somewhere then:

1. Run gradlew which should open BaseX 9.1.1 GUI
2. Run regex-j.xq in BaseX GUI. The query result should be displayed.
3. Close BaseX GUI.
4. Edit gradle.build and to change 9.1.1 to 9.1.2 on line 9
5. Run gradlew which should open BaseX 9.1.2 GUI
6. Run regex-j.xq in BaseX GUI. An error is thrown: `[FORX0001] Invalid regular flag: 'j'.`

It looks as though the "j" option was lost with changes to [RegExParser.java](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java) in commit d243b79

**Comment by ChristianGruen** [comment]
Thanks for the SSCCE. The bug has already been fixed. The background: The Java parser file is generated (via JavaCC) from the [regex.jj](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/javacc/regex.jj) parser file. By mistake, we updated the `.java` instead of the `.jj` file.

Feel free to add more comments if the [latest snapshot](http://files.basex.org/releases/latest/) does not work as expected.

**Comment by ChristianGruen** [comment]
Closing this (just reopen it if I missed something).
