### ISSUE TITLE
XQuery: Module imports are not transitive

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#2048]
The following function should raise an error:

```xquery
(: b.xqm :)
module namespace b  = 'b';
import module namespace c  = 'c'   at 'c.xqm';

(: c.xqm :)
module namespace c  = 'c';
declare function c:hello(){
  "can you see me now"
};

(: main.xq :)
import module namespace b  = 'b'   at 'b.xqm';
declare namespace c='c';
c:hello()
```

Original message: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg13873.html

**Comment by apb2006** [comment]
Example from https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg14507.html

In this case it appears an error, [XQST0049] Duplicate declaration of static variable, is raised by BaseX 9.7 when it should not be.
```
(: main.xq  :)
import module namespace u = "u" at 'u.xqm'; 
import module namespace c = "c" at 'data/c.xqm';
$u:path

(: u.xqm :)
module  namespace u="u";
declare variable $u:path:="somewhere";

(: data/c.xqm :)
module  namespace c="c";
import module namespace u = "u" at 'u.xqm'; (: cf '../u.xqm' :)
declare function c:foo(){
  "foo"
};

(: data/u.xqm:)
module  namespace u="u";
declare variable $u:path:="somewhere";
```
Saxon does not raise an error
`java -cp "%SAXON_HOME%/saxon9he-9.1.5.jar" net.sf.saxon.Query main.xq`

[issue.2048.zip](https://github.com/BaseXdb/basex/files/8549554/issue.2048.zip)

**Comment by GuntherRademacher** [comment]
> Saxon does not raise an error
> `java -cp "%SAXON_HOME%/saxon9he-9.1.5.jar" net.sf.saxon.Query main.xq`

Saxon apparently ignores the module in `data/u.xqm`. This can be easily verified by putting some syntactically invalid stuff into it. Presumably it ignores it, because the module URI has already been resolved before, and I think it rightfully does so, because of 

[4.12.3 Location URIs ](https://www.w3.org/TR/xquery-31/#id-module-handling-location-uris)
>  The mapping from location URIs to module source code or compiled code MAY be done in any way convenient to the implementation.

BaseX, on the other hand, processes input from `data/u.xqm`, and reports an error. The spec also says

[4.12.2 Multiple Modules with the same Namespace](https://www.w3.org/TR/xquery-31/#id-module-handling-multiple-same)
> Several different modules with the same target namespace can be used in the same query. The names of public variables and public functions must be unique within the [module contexts](https://www.w3.org/TR/xquery-31/#dt-module-context) of a query: that is, if two modules with the same target namespace URI are used in the same query, the names of the public variables and functions in their module contexts must not overlap.

In the given setup: two modules, same target namespace URI, same query, overlapping function names.

> No error due to duplicate variable or functions names should arise from the same module being imported more than once, so long as the absolute location URI is the same in each case. 

Different absolute location URIs thus may cause the error.
