### ISSUE TITLE
Feature proposal: Excel-specific CSV serialization

### ISSUE THREAD

**Issue by opax** [BaseXdb/basex#2066]
Importing CSV into Excel may be used to execute arbitrary code if not properly sanitized, see e.g. [here](https://owasp.org/www-community/attacks/CSV_Injection). The mitigation involves proper quoting and an additional `'` (apostrophe) at the beginning of the value. 

This special handling is only required if the CSV is meant to be imported into Excel. It is detrimental for other processing, where the apostrophe would be read as part of the field. It would therefore be nice to have a serialization option that activates Excel-specific quoting rules. The option could also change the defaults for `separator` and `lax` to `semicolon` and `no`, respectively, to be a one-stop option for safe Excel-conformant CSV serialization.

There have already been some discussion about Excel-specific problems with CSV serialization in #1518. It is possible that an additional apostrophe helps with these cases as well, but I did not test that.

The proposal is

* add an option `profile` to the CSV serialization/deserialization options. The only possible value for this option for now would be `excel`.
* If `profile=excel`, change the defaults for `separator` to `semicolon` and the defaults for `lax` to `no`
* If `profile=excel`, change the quoting rules so that values that start with `=`, `+`, `-`, `@`, Tab or CR are prepended with a single apostrophe before applying the usual quoting rules. It should be evaluated if the apostrophe should also be added if the values containing a forward slash.
* If `profile=excel`, change the parsing rules so that an apostrophe at the beginning of a value (after processing double quotes) is swallowed if the quoting rules would have appended it. This is probably the most controversial part of the proposal, but it would at least ensure that round-tripping data is consistent.

**Comment by ChristianGruen** [comment]
Thanks for the proposal.

It’s a real mess to get CSV properly serialized for Excel, and I’m pretty sure it’s impossible to achieve 100% round-tripping for arbitrary data. But your feedback certainly helps, and we should take security issues serious. I’ll have some more thoughts on this.

Two questions:
1. Regarding your particular comment on forward slashes, do you have an example or a reference to show why that would be required?
2. I’m not sure if I have understood the last rule of your proposal: If we swallow the apostrophe again after it would have been appended, what do we gain? Do you possibly have an example on how you think we should proceed?

One more thing we need to consider (our documentation doesn’t mention that yet) is the Excel separator, which depends on the regional settings of a system:

https://support.affinity.co/hc/en-us/articles/360044453711-How-to-open-CSV-files-with-the-correct-delimiter-separator

If we want to introduce a convenience `excel` option, we could try to determine the separator as follows:

```java
DecimalFormat df = (DecimalFormat) NumberFormat.getNumberInstance(Locale.getDefault());
char separator = df.getDecimalFormatSymbols().getDecimalSeparator() == ',' ? ';' : ','; 
```

… assuming that both BaseX and Excel are used in the same region.

**Comment by ChristianGruen** [comment]
I did some more experiments, and I particularly have concerns now to prepend apostrophes to `+` and `-` by default for Excel serializations. This is how the following CSV file …

```csv
=1+2;-3;===
'=1+2;'-3;'===
"=1+2"-3;"==="
'"=1+2";-3;'"==="
"'=1+2";"'-3";"'==="
"=1+2;-3;==="
"'=1+2;'-3;'==="
```

… will be interpreted by my German Excel instance:

![image](https://user-images.githubusercontent.com/196589/153401058-a7f0fa55-53e1-441f-91b1-8288e87e73cc.png)

I assume that none of the results are fully expected, but users might be surprised if negative integers needed to be preprocessed in Excel before they can be interpreted as numbers and used for further computations. And we need to consider that people may actually want to use special characters to trigger computations in Excel (I know of at least one BaseX user who did so).

Thus, I think it will be more intuitive to introduce a special option for the (un)escaping of special code injection characters.

I wonder if it’s still possible to trigger code injections with recent versions of Excel? My instance of Excel outputs a warning whenever I try to open a suspicious value, such as e.g. `=cmd|' /C calc'!xxx`.

**Comment by ChristianGruen** [comment]
Using patterns for numbers sounds like a pragmatic way out. We’re generally hesitant to interpret any user data and introduce special-casing code, though, as there are just too many use cases for which BaseX is used. In more serious applications, it’s better anyway to create Excel files via XQuery instead of relying on CSV.

I’ll give you feedback once I’ve introduced something that can be tested.

**Comment by ChristianGruen** [comment]
As we believe that malicious code should never end up in the result of a conversion process, we decided against sanitizing the data. Instead, we added a customizable regular expression option for rejecting illegal values. It can also be used to detect output that would possibly be interpreted or rendered by the target application in an unexpected way. In the example pattern in the documentation, I have adopted your idea to accept plus/minus signs followed by decimals: https://docs.basex.org/wiki/CSV_Module#Options.

A [new snapshot](https://files.basex.org/releases/latest/) is available.

**Comment by opax** [comment]
Sorry for the delay. I have looked at the snapshot and it works just as you described, and it certainly is a mitigation of the problem, so thank you!

Some thoughts about this solution:

* I fear many developers would be hesitant to use the `allow` option, as it introduces a new risk of runtime errors. To ensure that serialization succeeds, the data has to be pre-checked and quoted manually, which a security-aware developer could already do now, without the new option.
* There are many values that are not malicious code but still would be prohibited from being serialized (maybe an application wants to encode a positive sentiment with `+++` ). The `allow` option does not help with that.
* Maybe I misunderstand your comment about malicious code that should not never be the result of a conversion process. If some parts of the data of an application is user-controlled, it is by definition possible to enter code that might be malicious when used in some specific context (if improperly quoted). The `allow` option in this case changes a possible remote code injection to a possible denial of service, both of which are serious security problems.

I really do not want to come across as overly negative and appreciate the effort you have already put into this, but I am afraid that I still would have to implement the apostrophe-quoting by hand, to ensure that I would not have to worry about not-serializable data.

As an aside, the [page](https://support.affinity.co/hc/en-us/articles/360044453711-How-to-open-CSV-files-with-the-correct-delimiter-separator) about the ill-defined separator that you referenced, there is a possible solution by inserting e.g. `sep=,` as the first line of the CSV. This could also be handled with an excel-specific `profile`.

**Comment by ChristianGruen** [comment]
It’s certainly true that the new option might lead to runtime errors. Our rationale here:

* If data is malicious, it’s better to raise an error rather than masking it and passing it through.
* If data is not malicious, the error would be unexpected, but (we believe) it would be similarly confusing if such input was modified by appending it with an apostrophe (e.g. `'+++` instead of `+++`) such that the resulting data needs to be post-processed manually in the Excel sheet.

The more I think about our insightful discussion (thanks!), the more I doubt we should provide a workaround at all: The general issue here is that we’re trying to fix bugs that have been introduced by another application, and that have even worsened over the time. I am convinced it’s the task of the developers of the target software to find solutions such as not allowing code to be executed by default, as has been realized in newer versions of Excel.

One more flaw here is that we do not have access to (or I am not aware of) the full rule set of the target software how the input data will be processed; and I assume that this rule set has been changing in the past, and will further change, with different versions of the software.

A comparison with the recent log4j bug seems apparent: It’s a basic design error to make arbitrary input data executable, and it should always be up to the processing software to prevent bad things happening.

> As an aside, the [page](https://support.affinity.co/hc/en-us/articles/360044453711-How-to-open-CSV-files-with-the-correct-delimiter-separator) about the ill-defined separator that you referenced, there is a possible solution by inserting e.g. `sep=,` as the first line of the CSV. This could also be handled with an excel-specific `profile`.

True; I’ve seen that, and maybe I should think more about it. Thank you.

**Comment by ChristianGruen** [comment]
I’ll close this one; hope it’s ok.
