### ISSUE TITLE
XQuery: Regular expressions cont.

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#2240]
@GuntherRademacher I must take back my statement. I have indeed overlooked various tests that are now failing:

```xquery
(: expected: true :)
(every $s in tokenize('abcxyz}', ',') satisfies matches($s, '^(?:[a-\}]+)$')) and (every $s in tokenize('', ',') satisfies not(matches($s, '^(?:[a-\}]+)$'))),

(: expected: FORX0002 :)
matches('qwerty','[a-\\]'),
matches('qwerty','[a-\[]'),
matches('qwerty','foo([a-\d]*)bar'),
matches('qwerty','([5-\D]*)bar'),
matches('qwerty','foo([6-\s]*)bar'),
matches('qwerty','foo([c-\S]*)'),
matches('qwerty','foo([7-\w]*)'),
matches('qwerty','foo([a-\W]*)bar'),
matches('qwerty','([f-\p{Lu}]\w*)\s([\p{Lu}]\w*)'),
matches('qwerty','([1-\P{Ll}][\p{Ll}]*)\s([\P{Ll}][\p{Ll}]*)'),
(every $s in tokenize('a-x', ',') satisfies matches($s, '^(?:[a-a-x-x]+)$')) and
(every $s in tokenize('j,a-b', ',') satisfies not(matches($s, '^(?:[a-a-x-x]+)$')))
```

**Comment by GuntherRademacher** [comment]
Hi @ChristianGruen,

today I had a look at the XQuery tests relating to `fn:matches`. The test run reports a total of 7 problems:

```xml
<results>
  <fail>
    <test id="p294" regex="(a)|\1" input="x" result="y"/>
  </fail>
  <fail>
    <test id="p295" regex="(?:(b)?a)\1" input="a" result="y"/>
  </fail>
  <fail>
    <test id="p303" regex="^((.)?a\2)+$" input="babadad" result="y"/>
  </fail>
  <fail>
    <test id="p888" regex="([\d-z]+)" input="a0-za" result="Sy"/>
  </fail>
  <fail>
    <test id="p889" regex="([\d-z]+)" input="-" result="sc"/>
  </fail>
  <fail>
    <test id="p890" regex="([\d-\s]+)" input="a0- z" result="Sy"/>
  </fail>
  <fail>
    <test id="p891" regex="([\d-\s]+)" input="-" result="sc"/>
  </fail>
</results>
```
Tests p294, p295, and p303 fail, because the JRE's regex engine does not match backreferences, if the corresponding group has not been matched. The reason for not matching it is

   - in p294, the fact that the group is in a different branch of the surrounding `or`,
   - in p295 and p303, the group being optional, and unnecessary while matching.
   
I am proposing two changes for handling this:

   - removal of a backreference from the pattern, if it refers to a different branch of a surrounding `or` (will fix p294)
   - replacing an optional capturing group by a mandatory one, and wrapping its content into an optional non-capturing group (will fix p295 and p303). This change only needs to be done when the affected group is the target of a backreference.

I still have to work on the actual changes.

Tests p888-p891 IMHO are handled correctly by BaseX. In all cases the dash is preceded by a MultiCharEsc, such that it is not the meta character of an seRange, but represents a literal minus sign. I.e., the charGroup consists of a MultiCharEsc, an XmlCharIncDash (the dash) and either (in p888, p889) another XmlCharIncDash (the literal 'z'), or (in p890, p891) another MultiCharEsc. So these patterns should match dashes and the characters represented by the participating MultiCharEsc or XmlCharIncDash. And that's what they do.

The problem with p888-p891 is in the content of attribute 'result', which is 'Sy' and 'sc', but should be 'y' in these four cases. Am I overlooking something here? If not, should I file a PR for qt4tests (and qt3tests as well)?

Also, I think that the pattern in p303 is not valid with respect to the [specification of backreferences](https://www.w3.org/TR/xpath-functions-31/#back-references), which says

> The regular expression is invalid if a back-reference refers to a capturing sub-expression that does not exist or whose closing right parenthesis occurs after the back-reference.

Should we reject it? If yes, that would call for another change of qt4tests and qt3tests.

**Comment by ChristianGruen** [comment]
@GuntherRademacher Your analysis reads fine, as do your suggestions for fixing p294 and p295.

For the other patterns, it would be great if you could report this back to https://github.com/w3c/qt3tests (as suggested), either in an issue or via a pull request. Thanks!

**Comment by ChristianGruen** [comment]
PS: Commits to qt3tests are occasionally migrated to the qt4tests repository (see https://github.com/w3c/qt3tests/issues/54).

**Comment by GuntherRademacher** [comment]
Sorry for the confusion: the pattern in p303 of course *is* valid, because group 2 *is* closed before the back-reference occurs. Also the code to check for this condition is in place and works as it should.
