### ISSUE TITLE
CHOP Option: Switch default, or improve heuristics

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#913]
Discussions (just two of them):

  http://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg03964.html
  http://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/msg02502.html

**Comment by jmague** [comment]
In case someone is interested, we've modified the dba so that it offers to choose whether a new created database has the chop option set to true or false. The code is available in this repo: https://github.com/ahn-ens-lyon/dba

**Comment by ChristianGruen** [comment]
> In case someone is interested […]

Thanks ;) I’ll merge this very soon now (→ #1229).

**Comment by mingarao** [comment]
:+1 merging ?
it would be very usefull for us DH people because for most of our DBs need to preserve whitespaces.

**Comment by ChristianGruen** [comment]
It’s already online (see the discussion in #1229). If whitespace chopping is to be enforced globally, it needs to be put into the `web.xml` file…

**Comment by ChristianGruen** [comment]
Idea proposed by CMSMCQ (https://mailman.uni-konstanz.de/pipermail/basex-talk/2016-June/010870.html):

> Speaking for myself, I think a better heuristic than dropping all
whitespace-only text nodes and removing leading and trailing
whitespace would be dropping whitespace-only text nodes only 
if every text-node seen so far as a child of this parent has been
whitespace-only, and stripping leading whitespace only after a
start-tag and trailing whitespace only after an end-tag.
>
> The first would prevent the loss of the inter-word whitespace in
> 
>  `<p>This <em>is</em> <strong>IMPORTANT</strong></p>`

**Comment by graydon2014** [comment]
+1 CMSMCQ's heuristic.  That would be a definite improvement.

**Comment by ChristianGruen** [comment]
Related to the discussion:

```xquery
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "xml";
declare option output:indent "no";

let $string := ``[
<p> This <em>is</em> <strong> IMPORTANT</strong></p>
]``

let $xml := parse-xml($string) update {
  for $elem in .//*
  for $text in $elem/text()
  let $seen := $text/(self::text(), preceding-sibling::text())
  let $prec := $text/preceding-sibling::node()[1]
  (: is every text-node seen so far as a child
     of this parent whitespace-only? :)
  return if(empty($seen[normalize-space()])) then (
    (: yes: drop node :)
    delete node $text
  ) else (
    (: no: :)
    if(empty($prec)) then (
      (: does text node come after a start tag :)
      replace node $text with replace($text, '^\s+', '')
    ) else if($prec instance of element()) then (
      (: does text node come after an end tag :)
      replace node $text with replace($text, '\s+$', '')
    ) else ()
  )
}
return $xml
```

Feedback and suggestions how to improve it are welcome.

**Comment by graydon2014** [comment]
I think

declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization
";
declare option output:method "xml";
declare option output:indent "no";

let $string := ``[
<p> This <em>is</em> <strong> IMPORTANT</strong></p>
]``

let $xml := parse-xml($string) update {
  for $elem in .//*
  for $text in $elem/text()
  let $seen := $text/(self::text(), preceding-sibling::text())
  let $prec := $text/preceding::text()[1][not(matches(.,'\p{Z}'))]
  (: is every text-node seen so far as a child
     of this parent whitespace-only? :)
  return if(empty($seen[normalize-space()])) then (
    (: yes: drop node :)
    delete node $text
  ) else (
    (: no: :)
    if(empty($prec)) then (
      (: does text node come after a start tag :)
      replace node $text with replace($text, '^\s+', '')
    ) else if($prec instance of element()) then (
      (: does text node come after an end tag :)
      replace node $text with replace($text, '\s+$', '')
    ) else ()
  )
}
return $xml

works better on the example; how it works on more complex things (and if it
does what was originally suggested!) are open questions.

I think of the problem is fine when it's one level deep;  you want to test
that the immediately preceding text node isn't white-space-only.

If we have (I seem to have suppressed any detailed memory of multi-level
index term definitions in DITA....)

let $string := ``[
<p>Some words about an <index-term>
                                                 <level1>word</level1>
</index-term>
<anchor>word<alt>
There is a good deal of description here</alt>
</anchor>
And more words here, just because</p>
]``

I get
<p>Some words about an <index-term><level1>word</level1></index-term>
<anchor>word<alt>
There is a good deal of description here</alt></anchor>
And more words here, just because</p>

Which somewhat to my surprise isn't pretty but seems correct in terms of
where there's whitepsace.

-- Graydon

**Comment by gimsieke** [comment]
Because I stumbled across this again just yesterday: Wouldn’t the impending version leap to 10 be a good point to switch the default to CHOP=false?

(Aside: I’m not a fan of a heuristic that keeps WS in `<p>This <em>is</em> <strong>IMPORTANT</strong></p>` but drops it in `<p><em>Very</em> <strong>IMPORTANT</strong></p>`. The heuristic will possibly be better if it analyzes the whole document before chopping, but this might be too expensive – two passes, memory consumption, …)
`

**Comment by AndrewSales** [comment]
+1, x2

**Comment by graydon2014** [comment]
On Sat, May 14, 2022 at 03:18:55AM -0700, Andrew Sales scripsit:
> On Sat, 14 May 2022 at 06:00, Gerrit Imsieke ***@***.***> wrote:
> > Because I stumbled across this again just yesterday: Wouldn’t the
> > impending version leap to 10 be a good point to switch the default
> > to CHOP=false?
>
> +1, x2

Another vote in favour; changing the content shouldn't be the default —
<p>words more words <b>vital</b> <i>essential</i> words</p> should NOT
ever turn into <p>words more words <b>vital</b><i>essential</i>
words</p> — and the loss of intersitial white space is a dire outcome
with some content. (Never mind the clients who are absolutely determined
to have stable and meaningful white space in their XML.)

-- 
Graydon Saunders  | ***@***.***
Þæs oferéode, ðisses swá mæg.
-- Deor  ("That passed, so may this.")

**Comment by ChristianGruen** [comment]
Alright, you’ve convinced me to make this happen. We’ll also `indent=no` as default serialization parameter, too.

We’ll skip the idea of applying heuristics, as none of our experimental results were good enough for general use.
